[2025-02-09T02:25:42.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T02:25:42.781+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: basic_concepts.error_handling_task manual__2025-02-09T02:25:39.168814+00:00 [queued]>
[2025-02-09T02:25:42.790+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: basic_concepts.error_handling_task manual__2025-02-09T02:25:39.168814+00:00 [queued]>
[2025-02-09T02:25:42.791+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T02:25:42.806+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): error_handling_task> on 2025-02-09 02:25:39.168814+00:00
[2025-02-09T02:25:42.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T02:25:42.815+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2025-02-09T02:25:42.816+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'basic_concepts', 'error_handling_task', 'manual__2025-02-09T02:25:39.168814+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/01_basic_concepts.py', '--cfg-path', '/tmp/tmpdduj1d_d']
[2025-02-09T02:25:42.817+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask error_handling_task
[2025-02-09T02:25:42.870+0000] {task_command.py:467} INFO - Running <TaskInstance: basic_concepts.error_handling_task manual__2025-02-09T02:25:39.168814+00:00 [running]> on host 0370ed89eba8
[2025-02-09T02:25:42.950+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='basic_concepts' AIRFLOW_CTX_TASK_ID='error_handling_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T02:25:39.168814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T02:25:39.168814+00:00'
[2025-02-09T02:25:42.952+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T02:25:42.963+0000] {logging_mixin.py:190} INFO - Starting task...
[2025-02-09T02:25:42.964+0000] {python.py:240} INFO - Done. Returned value was: Task completed successfully
[2025-02-09T02:25:42.983+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T02:25:42.984+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=basic_concepts, task_id=error_handling_task, run_id=manual__2025-02-09T02:25:39.168814+00:00, execution_date=20250209T022539, start_date=20250209T022542, end_date=20250209T022542
[2025-02-09T02:25:43.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T02:25:43.043+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T02:25:43.045+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
