[2025-02-11T05:31:52.682+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T05:31:52.707+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_data_pipeline.upload_to_s3 manual__2025-02-11T05:31:32.434454+00:00 [queued]>
[2025-02-11T05:31:52.718+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_data_pipeline.upload_to_s3 manual__2025-02-11T05:31:32.434454+00:00 [queued]>
[2025-02-11T05:31:52.721+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-11T05:31:52.738+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 05:31:32.434454+00:00
[2025-02-11T05:31:52.748+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=242) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T05:31:52.750+0000] {standard_task_runner.py:72} INFO - Started process 244 to run task
[2025-02-11T05:31:52.751+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_data_pipeline', 'upload_to_s3', 'manual__2025-02-11T05:31:32.434454+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/zip.py', '--cfg-path', '/tmp/tmpmovhph2g']
[2025-02-11T05:31:52.755+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask upload_to_s3
[2025-02-11T05:31:52.814+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_data_pipeline.upload_to_s3 manual__2025-02-11T05:31:32.434454+00:00 [running]> on host bd02590d998b
[2025-02-11T05:31:52.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T05:31:32.434454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T05:31:32.434454+00:00'
[2025-02-11T05:31:52.904+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T05:31:52.928+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T05:31:52.938+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T05:31:52.939+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_data_pipeline, task_id=upload_to_s3, run_id=manual__2025-02-11T05:31:32.434454+00:00, execution_date=20250211T053132, start_date=20250211T053152, end_date=20250211T053152
[2025-02-11T05:31:52.967+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T05:31:53.005+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T05:31:53.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
