[2025-02-10T23:23:40.625+0000] {processor.py:186} INFO - Started process (PID=7972) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:23:40.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:23:40.628+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:23:40.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:23:40.689+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:23:40.680+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:23:40.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:23:40.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.105 seconds
[2025-02-10T23:24:11.390+0000] {processor.py:186} INFO - Started process (PID=7980) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:24:11.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:24:11.393+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:24:11.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:24:11.422+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:24:11.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:24:11.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:24:11.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.063 seconds
[2025-02-10T23:24:41.975+0000] {processor.py:186} INFO - Started process (PID=7989) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:24:41.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:24:41.979+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:24:41.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:24:42.013+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:24:42.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:24:42.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:24:42.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.070 seconds
[2025-02-10T23:25:12.569+0000] {processor.py:186} INFO - Started process (PID=8004) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:25:12.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:25:12.573+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:25:12.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:25:12.610+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:25:12.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:25:12.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:25:12.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.084 seconds
[2025-02-10T23:25:43.355+0000] {processor.py:186} INFO - Started process (PID=8013) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:25:43.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:25:43.359+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:25:43.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:25:43.407+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:25:43.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:25:43.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:25:43.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.091 seconds
[2025-02-10T23:26:14.254+0000] {processor.py:186} INFO - Started process (PID=8021) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:26:14.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:26:14.259+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:26:14.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:26:14.299+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:26:14.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:26:14.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:26:14.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.089 seconds
[2025-02-10T23:26:45.036+0000] {processor.py:186} INFO - Started process (PID=8030) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:26:45.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:26:45.042+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:26:45.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:26:45.095+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:26:45.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:26:45.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:26:45.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.106 seconds
[2025-02-10T23:27:16.083+0000] {processor.py:186} INFO - Started process (PID=8039) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:27:16.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:27:16.087+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:27:16.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:27:16.134+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:27:16.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:27:16.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:27:16.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.090 seconds
[2025-02-10T23:27:46.418+0000] {processor.py:186} INFO - Started process (PID=8048) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:27:46.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:27:46.424+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:27:46.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:27:46.480+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:27:46.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:27:46.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:27:46.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.111 seconds
[2025-02-10T23:28:16.813+0000] {processor.py:186} INFO - Started process (PID=8057) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:28:16.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:28:16.817+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:28:16.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:28:16.869+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:28:16.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:28:16.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:28:16.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.105 seconds
[2025-02-10T23:28:47.175+0000] {processor.py:186} INFO - Started process (PID=8066) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:28:47.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:28:47.180+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:28:47.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:28:47.236+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:28:47.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:28:47.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:28:47.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.108 seconds
[2025-02-10T23:29:17.349+0000] {processor.py:186} INFO - Started process (PID=8075) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:29:17.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:29:17.353+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:29:17.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:29:17.386+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:29:17.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:29:17.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:29:17.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.078 seconds
[2025-02-10T23:29:48.324+0000] {processor.py:186} INFO - Started process (PID=8084) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:29:48.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:29:48.328+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:29:48.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:29:48.366+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:29:48.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:29:48.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:29:48.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.082 seconds
[2025-02-10T23:30:19.074+0000] {processor.py:186} INFO - Started process (PID=8093) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:30:19.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:30:19.079+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:30:19.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:30:19.150+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:30:19.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:30:19.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:30:19.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.130 seconds
[2025-02-10T23:30:49.992+0000] {processor.py:186} INFO - Started process (PID=8102) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:30:49.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:30:49.998+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:30:49.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:30:50.055+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:30:50.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:30:50.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:30:50.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.102 seconds
[2025-02-10T23:31:20.774+0000] {processor.py:186} INFO - Started process (PID=8111) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:31:20.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:31:20.779+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:31:20.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:31:20.844+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:31:20.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:31:20.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:31:20.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.114 seconds
[2025-02-10T23:31:51.751+0000] {processor.py:186} INFO - Started process (PID=8120) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:31:51.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:31:51.756+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:31:51.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:31:51.835+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:31:51.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:31:51.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:31:51.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.124 seconds
[2025-02-10T23:32:22.799+0000] {processor.py:186} INFO - Started process (PID=8129) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:32:22.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:32:22.804+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:32:22.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:32:22.859+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:32:22.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:32:22.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:32:22.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.110 seconds
[2025-02-10T23:32:53.746+0000] {processor.py:186} INFO - Started process (PID=8138) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:32:53.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:32:53.751+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:32:53.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:32:53.800+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:32:53.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:32:53.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:32:53.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.104 seconds
[2025-02-10T23:33:24.779+0000] {processor.py:186} INFO - Started process (PID=8147) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:33:24.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:33:24.783+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:33:24.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:33:24.856+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:33:24.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:33:24.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:33:24.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.121 seconds
[2025-02-10T23:33:54.992+0000] {processor.py:186} INFO - Started process (PID=8156) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:33:54.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:33:54.997+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:33:54.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:33:55.085+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:33:55.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:33:55.094+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:33:55.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.155 seconds
[2025-02-10T23:34:25.257+0000] {processor.py:186} INFO - Started process (PID=8165) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:34:25.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:34:25.263+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:34:25.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:34:25.324+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:34:25.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:34:25.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:34:25.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.124 seconds
[2025-02-10T23:34:55.504+0000] {processor.py:186} INFO - Started process (PID=8173) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:34:55.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:34:55.510+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:34:55.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:34:55.589+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:34:55.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:34:55.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:34:55.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.141 seconds
[2025-02-10T23:35:25.743+0000] {processor.py:186} INFO - Started process (PID=8182) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:35:25.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:35:25.747+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:35:25.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:35:25.796+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:35:25.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:35:25.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:35:25.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.093 seconds
[2025-02-10T23:35:56.781+0000] {processor.py:186} INFO - Started process (PID=8191) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:35:56.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:35:56.789+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:35:56.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:35:56.879+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:35:56.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:35:56.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:35:56.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.150 seconds
[2025-02-10T23:37:21.587+0000] {processor.py:186} INFO - Started process (PID=8200) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:37:21.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:37:21.592+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:37:21.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:37:21.651+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:37:21.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:37:21.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:37:21.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.104 seconds
[2025-02-10T23:37:52.438+0000] {processor.py:186} INFO - Started process (PID=8209) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:37:52.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:37:52.444+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:37:52.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:37:52.491+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:37:52.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:37:52.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:37:52.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.096 seconds
[2025-02-10T23:38:23.343+0000] {processor.py:186} INFO - Started process (PID=8218) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:38:23.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:38:23.348+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:38:23.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:38:23.423+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:38:23.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:38:23.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:38:23.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.132 seconds
[2025-02-10T23:38:54.342+0000] {processor.py:186} INFO - Started process (PID=8227) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:38:54.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:38:54.347+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:38:54.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:38:54.436+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:38:54.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:38:54.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:38:54.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.152 seconds
[2025-02-10T23:39:25.338+0000] {processor.py:186} INFO - Started process (PID=8237) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:39:25.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:39:25.342+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:39:25.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:39:25.394+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:39:25.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:39:25.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:39:25.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.097 seconds
[2025-02-10T23:39:56.287+0000] {processor.py:186} INFO - Started process (PID=8246) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:39:56.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:39:56.295+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:39:56.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:39:56.363+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:39:56.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:39:56.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:39:56.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.132 seconds
[2025-02-10T23:40:27.250+0000] {processor.py:186} INFO - Started process (PID=8255) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:40:27.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:40:27.254+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:40:27.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:40:27.311+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:40:27.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:40:27.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:40:27.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.113 seconds
[2025-02-10T23:40:58.079+0000] {processor.py:186} INFO - Started process (PID=8264) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:40:58.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:40:58.084+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:40:58.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:40:58.111+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:40:58.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:40:58.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:40:58.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.074 seconds
[2025-02-10T23:41:28.864+0000] {processor.py:186} INFO - Started process (PID=8273) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:41:28.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:41:28.868+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:41:28.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:41:28.904+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:41:28.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:41:28.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:41:28.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.079 seconds
[2025-02-10T23:41:59.543+0000] {processor.py:186} INFO - Started process (PID=8282) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:41:59.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:41:59.547+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:41:59.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:41:59.596+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:41:59.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:41:59.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:41:59.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.094 seconds
[2025-02-10T23:42:30.193+0000] {processor.py:186} INFO - Started process (PID=8291) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:42:30.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:42:30.197+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:42:30.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:42:30.219+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:42:30.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:42:30.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:42:30.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.056 seconds
[2025-02-10T23:43:01.198+0000] {processor.py:186} INFO - Started process (PID=8300) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:43:01.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:43:01.207+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:43:01.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:43:01.271+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:43:01.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:43:01.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:43:01.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.147 seconds
[2025-02-10T23:43:32.391+0000] {processor.py:186} INFO - Started process (PID=8308) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:43:32.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:43:32.398+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:43:32.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:43:32.456+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:43:32.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:43:32.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:43:32.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.126 seconds
[2025-02-10T23:44:02.707+0000] {processor.py:186} INFO - Started process (PID=8316) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:44:02.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:44:02.715+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:44:02.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:44:02.785+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:44:02.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:44:02.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:44:02.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.146 seconds
[2025-02-10T23:44:33.009+0000] {processor.py:186} INFO - Started process (PID=8325) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:44:33.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:44:33.018+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:44:33.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:44:33.083+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:44:33.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:44:33.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:44:33.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.137 seconds
[2025-02-10T23:45:04.062+0000] {processor.py:186} INFO - Started process (PID=8334) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:45:04.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:45:04.069+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:45:04.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:45:04.135+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:45:04.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:45:04.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:45:04.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.135 seconds
[2025-02-10T23:45:35.147+0000] {processor.py:186} INFO - Started process (PID=8343) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:45:35.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:45:35.155+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:45:35.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:45:35.197+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:45:35.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:45:35.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:45:35.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.116 seconds
[2025-02-10T23:46:06.239+0000] {processor.py:186} INFO - Started process (PID=8353) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:46:06.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:46:06.250+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:46:06.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:46:06.317+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:46:06.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:46:06.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:46:06.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.148 seconds
[2025-02-10T23:46:37.361+0000] {processor.py:186} INFO - Started process (PID=8362) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:46:37.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:46:37.370+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:46:37.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:46:37.459+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:46:37.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:46:37.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:46:37.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.165 seconds
[2025-02-10T23:47:08.375+0000] {processor.py:186} INFO - Started process (PID=8371) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:47:08.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:47:08.383+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:47:08.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:47:08.441+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:47:08.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:47:08.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:47:08.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.133 seconds
[2025-02-10T23:47:39.425+0000] {processor.py:186} INFO - Started process (PID=8380) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:47:39.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:47:39.430+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:47:39.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:47:39.479+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:47:39.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:47:39.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:47:39.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.108 seconds
[2025-02-10T23:50:34.350+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:50:34.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:50:34.363+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:50:34.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:50:34.418+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:50:34.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:50:34.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:50:34.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.135 seconds
[2025-02-10T23:51:05.559+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:51:05.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:51:05.567+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:51:05.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:51:05.609+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:51:05.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:51:05.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:51:05.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.106 seconds
[2025-02-10T23:51:36.773+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:51:36.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:51:36.781+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:51:36.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:51:36.831+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:51:36.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:51:36.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:51:36.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.118 seconds
[2025-02-10T23:52:07.837+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:52:07.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:52:07.844+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:52:07.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:52:07.890+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:52:07.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:52:07.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:52:07.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.105 seconds
[2025-02-10T23:52:38.072+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:52:38.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:52:38.082+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:52:38.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:52:38.141+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:52:38.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:52:38.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:52:38.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.122 seconds
[2025-02-10T23:53:09.095+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:53:09.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:53:09.104+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:53:09.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:53:09.160+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:53:09.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:53:09.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:53:09.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.120 seconds
[2025-02-10T23:53:40.185+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:53:40.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:53:40.197+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:53:40.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:53:40.252+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:53:40.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:53:40.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:53:40.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.158 seconds
[2025-02-10T23:54:11.238+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:54:11.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:54:11.249+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:54:11.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:54:11.326+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:54:11.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:54:11.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:54:11.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.167 seconds
[2025-02-10T23:54:42.376+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:54:42.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:54:42.386+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:54:42.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:54:42.455+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:54:42.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:54:42.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:54:42.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.148 seconds
[2025-02-10T23:55:13.524+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:55:13.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:55:13.531+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:55:13.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:55:13.578+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:55:13.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:55:13.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:55:13.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.102 seconds
[2025-02-10T23:55:43.794+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:55:43.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:55:43.801+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:55:43.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:55:43.846+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:55:43.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:55:43.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:55:43.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.110 seconds
[2025-02-10T23:56:14.065+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:56:14.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:56:14.071+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:56:14.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:56:14.103+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:56:14.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:56:14.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:56:14.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.082 seconds
[2025-02-10T23:56:44.981+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:56:44.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:56:44.987+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:56:44.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:56:45.034+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:56:45.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:56:45.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:56:45.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.104 seconds
[2025-02-10T23:57:16.069+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:57:16.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:57:16.080+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:57:16.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:57:16.137+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:57:16.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:57:16.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:57:16.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.121 seconds
[2025-02-10T23:57:47.070+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:57:47.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:57:47.081+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:57:47.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:57:47.140+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:57:47.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:57:47.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:57:47.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.138 seconds
[2025-02-10T23:58:18.223+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:58:18.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:58:18.232+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:58:18.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:58:18.301+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:58:18.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:58:18.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:58:18.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.161 seconds
[2025-02-10T23:58:48.620+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:58:48.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:58:48.633+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:58:48.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:58:48.700+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:58:48.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:58:48.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:58:48.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.175 seconds
[2025-02-10T23:59:19.121+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:59:19.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:59:19.135+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:59:19.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:59:19.187+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:59:19.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:59:19.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:59:19.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.128 seconds
[2025-02-10T23:59:49.513+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/zip.py
[2025-02-10T23:59:49.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/zip.py for tasks to queue
[2025-02-10T23:59:49.525+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:59:49.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/zip.py
[2025-02-10T23:59:49.577+0000] {logging_mixin.py:190} INFO - [2025-02-10T23:59:49.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/zip.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/zip.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-02-10T23:59:49.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/zip.py
[2025-02-10T23:59:49.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/zip.py took 0.147 seconds
